// Writes each app's build-info.ts with the current git sha + build time, so the
// running bundle can show which build it is. Embedded at build time rather than
// fetched at runtime on purpose: a stale cached page then shows its OWN old
// stamp, which is the whole point — it lets you spot a stale cache instead of
// being reassured by the server's current version. The generated files are
// gitignored.
//
// Mirrors life's scripts/stamp-version.mjs, which is recall's adapted for a
// Docker build with no .git in context: CI passes the commit as GIT_SHA (see
// Dockerfile + .github/workflows/build.yml); local dev falls back to `git`.
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));

/** The one app in this workspace. */
const APPS = [join(here, '..', 'src', 'app', 'build-info.ts')];

function git(cmd) {
  try {
    return execSync(`git ${cmd}`, { encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
}

// Prefer the CI-provided commit (Docker has no .git); else read it locally.
const envSha = (process.env.GIT_SHA ?? '').slice(0, 7);
const sha = envSha || git('rev-parse --short HEAD') || 'nogit';
// A gitignored build-info.ts won't dirty the tree; any real uncommitted change
// marks the build. (Only meaningful for local builds — Docker has no git.)
const dirty = git('status --porcelain') ? '+' : '';
const builtAt = new Date().toISOString();

for (const out of APPS) {
  writeFileSync(
    out,
    `// Generated by scripts/stamp-version.mjs at build time. Do not edit — gitignored.
export const BUILD_INFO = {
  sha: '${sha}${dirty}',
  builtAt: '${builtAt}',
} as const;
`,
  );
}
console.log(`stamped build-info: ${sha}${dirty} @ ${builtAt}`);
